"""Change Base

Revision ID: 200c2828ab10
Revises: 6d53c3324b4d
Create Date: 2023-09-12 14:46:51.408996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200c2828ab10'
down_revision = '6d53c3324b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
